from app.models_frontend import antenna
from app.models_frontend import base_model
from app.models_frontend import carrier
from app.models_frontend import carrier
from app.models_frontend import city
from app.models_frontend import gsm_count
from app.models_frontend import gsm_signal
from app.models_frontend import network_type
from app.models_frontend import ranking
from app.models_frontend import region
from app.models_frontend import user
